plugins {
    id 'java'
}

group = 'com.liskcell.easypunish'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.luckperms.net/' }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-nowarn', '-Xlint:none']
    options.encoding = 'UTF-8'
    options.release = 21
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
    compileOnly 'net.luckperms:api:5.4'
}
